Add source to NEF
neo-project/proposals pull request #148
Opened 2022-04-04 12:02 UTC by shargon

2022-04-04 15:27 UTC, lllwvlvwlll commented
@shargon do you have some examples of how this can be used?  Is there a standard format (like absolute path to the entrypoint) that this is being implemented alongside?

2022-04-04 22:31 UTC, devhawk requested changes
This information is already in the debug info. https://github.com/devhawk/proposals/blob/devhawk/debug-info/nep-19.md#documents

I don't see the value of putting it in the NEF file

2022-04-05 08:07 UTC, shargon commented
> I don't see the value of putting it in the NEF file

It's already in the nef file

2022-04-05 08:09 UTC, shargon commented
@lllwvlvwlll it was introduced in https://github.com/neo-project/neo/pull/2605 , I think that it must be an absolute url.

2022-04-05 16:57 UTC, devhawk commented
> It's already in the nef file https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/NefFile.cs#L57

Then I agree it should be in the NEP

2022-04-05 16:57 UTC, devhawk approved these changes

2022-04-07 08:35 UTC, erikzhang commented on nep-16.mediawiki
>    2-byte reserve;
Then it becomes 1 byte.

2022-04-07 10:37 UTC, shargon commented on nep-16.mediawiki
>    2-byte reserve;
At least one, but it can be more

2022-04-07 23:03 UTC, erikzhang approved these changes

2022-04-07 23:03 UTC, merged